### ISSUE TITLE
Error on langage selection

### ISSUE THREAD

**Issue by Yogui79** [Devenet/AdventCalendar#24]
when I want to change the langage to FR it does'nt work,
I investigate and found that when I replace mb_strtolower with strtolower it works

thank you for the job you do

regards

**Comment by Devenet** [comment]
Hum, this issue seems odd.

The function [`mb_strtolower`]() is the same as `strtolower` expect it supports Unicode.
> By contrast to `strtolower()`, 'alphabetic' is determined by the Unicode character properties. Thus the behaviour of this function is not affected by locale settings and it can convert any characters that have 'alphabetic' property, such as A-umlaut (Ä). 

Because it is used in a no-unicode context, I have replaced it with `strtolower`.
