### ISSUE TITLE
The generated settings.json use UTF-8 with BOM instead of UTF-8 without BOM

### ISSUE THREAD

**Issue by fscholdei** [Devenet/AdventCalendar#29]
Maybe it's just me, but the json_decode call when reading the settings.json always receives null if the file contains valid JSON with BOM. I had no problems with calendar.json. On [StackOverflow](https://stackoverflow.com/a/38471277) the problem is also described.

**Comment by Devenet** [comment]
I never had this problem, probably because I saved my file in UTF-8 without BOM.
Do you have the same problem when you generate the `settings.json` file from [the online generator](https://www.devenet.eu/advent/generator/#settings)?

**Workaround** Save again your file encoded as UTF-8 without BOM.

**Comment by fscholdei** [comment]
Well, I could have mentioned that at the beginning. Yes, the generated file doesn't work for me either.

**Comment by Devenet** [comment]
I updated the generator script to force the downloaded files `settings.json` and `calendar.json` to be in UTF-8 without BOM.

The [the online generator](https://www.devenet.eu/advent/generator/#settings) has been updated, but you may need to force update the page to clear the the script file's cache.
