### ISSUE TITLE
GIFs over ~50mb do not show up

### ISSUE THREAD

**Issue by daylamtayari** [Devenet/AdventCalendar#30]
GIFs that are over ~50 mb do not show up on the actual webpage.
If the GIF is over ~50 mb, it will simply not show anything, it won't show the "It's a surprise" image for when there is no image associated for that particular day, just nothing. 
GIFs that are below ~50 mb show up totally fine.

**Comment by Devenet** [comment]
Hi @daylamtayari

I reproduced the same behaviour on my webserver.

However, this is a limitation of the PHP engine, not the application.  
In my `php.ini` file I have the default configuration for the `output_buffering` parameter:
```
output_buffering = 4096
```
<img width="601" alt="Screenshot php.ini file" src="https://user-images.githubusercontent.com/1587913/103286195-20662880-49e0-11eb-9ed9-251a4544ade4.png">

That means the file served can not be over 4096 bytes, the ~ 50 MB limit you noticed.  
By changing it to `Off` my [99 MB GIF](http://www.astronight.com/022008/022008LunaEclispe.gif) is well displayed.

**Comment by Devenet** [comment]
Another solution would be to use another function that `file_get_contents()` to read and serve the file. Seems a bit complex for now.

- https://stackoverflow.com/a/21936954/2337765
- https://stackoverflow.com/a/54704668/2337765
